# languages.py (Final Sürüm - Tüm Özellikler Dahil)

TRANSLATIONS = {
    "tr": {
        "window_title": "SteamF12TooL",
        "preview_placeholder": "Seçilen Resim Burada Görünecek",
        "select_image_button": "1. Resim/Resimler Seç",
        "multiple_images_selected": "{} resim seçildi",
        "upload_progress": "Yükleniyor: {}/{}",
        "batch_upload_complete": "{} resim başarıyla yüklendi.",
        "scan_games_button": "2. Steam Oyunlarını Tara",
        "scan_games_button_scanning": "Taranıyor, lütfen bekleyin...",
        "manual_folder_button": "veya Manuel Klasör Seç",
        "upload_button": "SEÇİLENLERİ YÜKLE",
        "dark_mode_switch": "Koyu Mod",
        "edit_tools_label": "Düzenleme Araçları (Sadece tek resim seçiliyken aktif)",
        "rotate_left_button": "Sola Döndür",
        "rotate_right_button": "Sağa Döndür",
        "reset_button": "Sıfırla",
        "crop_button": "Kırp",
        "crop_window_title": "Resmi Kırp",
        "apply_button": "Uygula",
        "cancel_button": "İptal",
        "donate_button": "Bağış Yap",
        "donate_window_title": "Destek Olun",
        "donate_main_text": "Bu projeyi beğendiyseniz, bir kahve ısmarlayarak\ndestek olabilirsiniz. Desteğiniz için teşekkürler!",
        "donate_iban_label": "IBAN:",
        "donate_copy_button": "IBAN'ı Kopyala",
        "donate_copy_success": "IBAN panoya kopyalandı!",
        "no_image_selected": "Henüz resim seçilmedi.",
        "no_folder_selected": "Oyun seçin veya manuel olarak belirleyin.",
        "game_combobox_default": "Önce oyunları taratın...",
        "game_combobox_select": "Bir oyun seçin...",
        "game_combobox_fail": "Tarama başarısız oldu.",
        "select_profile": "Steam Profili",
        "no_profiles_found": "Hiç Steam profili bulunamadı.",
        "profile_fallback": "Profil ({})",
        "success": "Başarılı",
        "error": "Hata",
        "warning": "Uyarı",
        "info": "Bilgi",
        "fix": "Düzeltme",
        "games_found_message": "{} oyun bulundu!",
        "select_image_warning": "Lütfen önce bir veya daha fazla resim dosyası seçin.",
        "select_folder_warning": "Lütfen geçerli bir oyun veya klasör seçin.",
        "upload_success_message": "Ekran görüntüsü başarıyla eklendi:\n\n{}",
        "thumbnail_error": "Thumbnail oluşturulurken bir hata oluştu.",
        "unexpected_error": "Beklenmedik bir hata oluştu: {}",
        "steam_not_found": "Steam kurulumu bulunamadı.",
        "applist_download_fail": "Steam oyun listesi indirilemedi.",
        "applist_process_fail": "Oyun listesi işlenemedi: {}",
        "userdata_folder_not_found": "'userdata' klasörü bulunamadı.",
        "no_games_with_screenshots_found": "Ekran görüntüsü klasörüne sahip oyun bulunamadı.",
        "unknown_game": "Bilinmeyen Oyun (ID: {})",
        "thumbnail_fix_message": "'thumbnails' klasörü seçildi. Ana klasör otomatik olarak ayarlandı."
    },
    "ar": {
        "window_title": "SteamF12TooL",
        "preview_placeholder": "الصورة المحددة ستظهر هنا",
        "select_image_button": "1. اختر صورة (صور)",
        "multiple_images_selected": "تم تحديد {} صورة",
        "upload_progress": "جاري الرفع: {}/{}",
        "batch_upload_complete": "تم رفع {} صورة بنجاح.",
        "scan_games_button": "2. ابحث عن ألعاب Steam",
        "scan_games_button_scanning": "جاري البحث، يرجى الانتظار...",
        "manual_folder_button": "أو اختر المجلد يدويًا",
        "upload_button": "رفع الملفات المحددة",
        "dark_mode_switch": "الوضع الداكن",
        "edit_tools_label": "أدوات التعديل (نشط مع صورة واحدة فقط)",
        "rotate_left_button": "تدوير لليسار",
        "rotate_right_button": "تدوير لليمين",
        "reset_button": "إعادة تعيين",
        "crop_button": "قص",
        "crop_window_title": "قص الصورة",
        "apply_button": "تطبيق",
        "cancel_button": "إلغاء",
        "donate_button": "تبرع",
        "donate_window_title": "دعم المشروع",
        "donate_main_text": "إذا أعجبك هذا المشروع، يمكنك دعمه\nبشراء قهوة لي. شكراً لدعمك!",
        "donate_iban_label": "IBAN:",
        "donate_copy_button": "نسخ IBAN",
        "donate_copy_success": "تم نسخ IBAN إلى الحافظة!",
        "no_image_selected": "لم يتم اختيار صورة بعد.",
        "no_folder_selected": "اختر لعبة أو حدد مجلدًا يدويًا.",
        "game_combobox_default": "ابحث عن الألعاب أولاً...",
        "game_combobox_select": "اختر لعبة...",
        "game_combobox_fail": "فشل البحث.",
        "select_profile": "ملف تعريف Steam",
        "no_profiles_found": "لم يتم العثور على ملفات تعريف Steam.",
        "profile_fallback": "ملف تعريف ({})",
        "success": "نجاح",
        "error": "خطأ",
        "warning": "تحذير",
        "info": "معلومات",
        "fix": "تصحيح",
        "games_found_message": "تم العثور على {} لعبة!",
        "select_image_warning": "يرجى اختيار ملف صورة واحد أو أكثر أولاً.",
        "select_folder_warning": "يرجى اختيار لعبة أو مجلد صالح.",
        "upload_success_message": "تمت إضافة لقطة الشاشة بنجاح:\n\n{}",
        "thumbnail_error": "حدث خطأ أثناء إنشاء الصورة المصغرة.",
        "unexpected_error": "حدث خطأ غير متوقع: {}",
        "steam_not_found": "لم يتم العثور على تثبيت Steam.",
        "applist_download_fail": "لا يمكن تنزيل قائمة ألعاب Steam.",
        "applist_process_fail": "لا يمكن معالجة قائمة الألعاب: {}",
        "userdata_folder_not_found": "مجلد 'userdata' غير موجود.",
        "no_games_with_screenshots_found": "لم يتم العثور على ألعاب بها مجلدات لقطات شاشة.",
        "unknown_game": "لعبة غير معروفة (ID: {})",
        "thumbnail_fix_message": "تم تحديد مجلد 'thumbnails'. تم تعيين المجلد الأصل تلقائيًا."
    },
    "en": {
        "window_title": "SteamF12TooL",
        "preview_placeholder": "Selected Image Will Appear Here",
        "select_image_button": "1. Select Image(s)",
        "multiple_images_selected": "{} images selected",
        "upload_progress": "Uploading: {}/{}",
        "batch_upload_complete": "Successfully uploaded {} images.",
        "scan_games_button": "2. Scan Steam Games",
        "scan_games_button_scanning": "Scanning, please wait...",
        "manual_folder_button": "or Select Folder Manually",
        "upload_button": "UPLOAD SELECTED",
        "dark_mode_switch": "Dark Mode",
        "edit_tools_label": "Editing Tools (Active only with a single image)",
        "rotate_left_button": "Rotate Left",
        "rotate_right_button": "Rotate Right",
        "reset_button": "Reset",
        "crop_button": "Crop",
        "crop_window_title": "Crop Image",
        "apply_button": "Apply",
        "cancel_button": "Cancel",
        "donate_button": "Donate",
        "donate_window_title": "Support the Project",
        "donate_main_text": "If you like this project, you can support it by\nbuying me a coffee. Thank you for your support!",
        "donate_iban_label": "IBAN:",
        "donate_copy_button": "Copy IBAN",
        "donate_copy_success": "IBAN copied to clipboard!",
        "no_image_selected": "No image selected yet.",
        "no_folder_selected": "Select a game or choose a folder manually.",
        "game_combobox_default": "Scan for games first...",
        "game_combobox_select": "Select a game...",
        "game_combobox_fail": "Scan failed.",
        "select_profile": "Steam Profile",
        "no_profiles_found": "No Steam profiles found.",
        "profile_fallback": "Profile ({})",
        "success": "Success",
        "error": "Error",
        "warning": "Warning",
        "info": "Information",
        "fix": "Correction",
        "games_found_message": "Found {} games!",
        "select_image_warning": "Please select one or more image files first.",
        "select_folder_warning": "Please select a valid game or folder.",
        "upload_success_message": "Screenshot added successfully:\n\n{}",
        "thumbnail_error": "An error occurred while creating the thumbnail.",
        "unexpected_error": "An unexpected error occurred: {}",
        "steam_not_found": "Steam installation not found.",
        "applist_download_fail": "Could not download the Steam game list.",
        "applist_process_fail": "Could not process the game list: {}",
        "userdata_folder_not_found": "'userdata' folder not found.",
        "no_games_with_screenshots_found": "No games with screenshot folders were found.",
        "unknown_game": "Unknown Game (ID: {})",
        "thumbnail_fix_message": "'thumbnails' folder was selected. The parent folder has been set automatically."
    },
    "it": {
        "window_title": "SteamF12TooL",
        "preview_placeholder": "L'immagine Selezionata Apparirà Qui",
        "select_image_button": "1. Seleziona Immagine(i)",
        "multiple_images_selected": "{} immagini selezionate",
        "upload_progress": "Caricamento: {}/{}",
        "batch_upload_complete": "{} immagini caricate con successo.",
        "scan_games_button": "2. Scansiona Giochi di Steam",
        "scan_games_button_scanning": "Scansione, attendere...",
        "manual_folder_button": "o Seleziona Cartella Manualmente",
        "upload_button": "CARICA SELEZIONATI",
        "dark_mode_switch": "Modalità Scura",
        "edit_tools_label": "Strumenti di Modifica (Solo con immagine singola)",
        "rotate_left_button": "Ruota a Sinistra",
        "rotate_right_button": "Ruota a Destra",
        "reset_button": "Ripristina",
        "crop_button": "Ritaglia",
        "crop_window_title": "Ritaglia Immagine",
        "apply_button": "Applica",
        "cancel_button": "Annulla",
        "donate_button": "Donazione",
        "donate_window_title": "Sostieni il Progetto",
        "donate_main_text": "Se ti piace questo progetto, puoi sostenerlo\noffrendomi un caffè. Grazie per il tuo supporto!",
        "donate_iban_label": "IBAN:",
        "donate_copy_button": "Copia IBAN",
        "donate_copy_success": "IBAN copiato negli appunti!",
        "no_image_selected": "Nessuna immagine selezionata.",
        "no_folder_selected": "Seleziona un gioco o una cartella.",
        "game_combobox_default": "Scansiona prima i giochi...",
        "game_combobox_select": "Seleziona un gioco...",
        "game_combobox_fail": "Scansione fallita.",
        "select_profile": "Profilo Steam",
        "no_profiles_found": "Nessun profilo Steam trovato.",
        "profile_fallback": "Profilo ({})",
        "success": "Successo",
        "error": "Errore",
        "warning": "Avviso",
        "info": "Informazione",
        "fix": "Correzione",
        "games_found_message": "Trovati {} giochi!",
        "select_image_warning": "Seleziona prima uno o più file immagine.",
        "select_folder_warning": "Seleziona un gioco o una cartella valida.",
        "upload_success_message": "Screenshot aggiunto con successo:\n\n{}",
        "thumbnail_error": "Errore durante la creazione della miniatura.",
        "unexpected_error": "Si è verificato un errore imprevisto: {}",
        "steam_not_found": "Installazione di Steam non trovata.",
        "applist_download_fail": "Impossibile scaricare l'elenco dei giochi di Steam.",
        "applist_process_fail": "Impossibile elaborare l'elenco dei giochi: {}",
        "userdata_folder_not_found": "Cartella 'userdata' non trovata.",
        "no_games_with_screenshots_found": "Nessun gioco con cartelle di screenshot trovato.",
        "unknown_game": "Gioco Sconosciuto (ID: {})",
        "thumbnail_fix_message": "È stata selezionata la cartella 'thumbnails'. La cartella principale è stata impostata."
    },
    "jp": {
        "window_title": "SteamF12TooL",
        "preview_placeholder": "選択した画像がここに表示されます",
        "select_image_button": "1. 画像を選択",
        "multiple_images_selected": "{}枚の画像が選択されました",
        "upload_progress": "アップロード中: {}/{}",
        "batch_upload_complete": "{}枚の画像のアップロードに成功しました。",
        "scan_games_button": "2. Steamゲームをスキャン",
        "scan_games_button_scanning": "スキャン中、お待ちください...",
        "manual_folder_button": "または手動でフォルダを選択",
        "upload_button": "選択したものをアップロード",
        "dark_mode_switch": "ダークモード",
        "edit_tools_label": "編集ツール (単一画像のみ有効)",
        "rotate_left_button": "左に回転",
        "rotate_right_button": "右に回転",
        "reset_button": "リセット",
        "crop_button": "トリミング",
        "crop_window_title": "画像をトリミング",
        "apply_button": "適用",
        "cancel_button": "キャンセル",
        "donate_button": "寄付",
        "donate_window_title": "プロジェクトを支援",
        "donate_main_text": "このプロジェクトが気に入ったら、コーヒー一杯で\n支援できます。ご支援ありがとうございます！",
        "donate_iban_label": "IBAN:",
        "donate_copy_button": "IBANをコピー",
        "donate_copy_success": "IBANがクリップボードにコピーされました！",
        "no_image_selected": "画像が選択されていません。",
        "no_folder_selected": "ゲームを選択するか、フォルダを手動で選択してください。",
        "game_combobox_default": "最初にゲームをスキャンしてください...",
        "game_combobox_select": "ゲームを選択...",
        "game_combobox_fail": "スキャンに失敗しました。",
        "select_profile": "Steamプロファイル",
        "no_profiles_found": "Steamプロファイルが見つかりません。",
        "profile_fallback": "プロファイル ({})",
        "success": "成功",
        "error": "エラー",
        "warning": "警告",
        "info": "情報",
        "fix": "修正",
        "games_found_message": "{}個のゲームが見つかりました！",
        "select_image_warning": "最初に1つ以上の画像ファイルを選択してください。",
        "select_folder_warning": "有効なゲームまたはフォルダを選択してください。",
        "upload_success_message": "スクリーンショットが正常に追加されました:\n\n{}",
        "thumbnail_error": "サムネイルの作成中にエラーが発生しました。",
        "unexpected_error": "予期せぬエラーが発生しました: {}",
        "steam_not_found": "Steamのインストールが見つかりません。",
        "applist_download_fail": "Steamゲームリストをダウンロードできませんでした。",
        "applist_process_fail": "ゲームリストを処理できませんでした: {}",
        "userdata_folder_not_found": "'userdata'フォルダが見つかりません。",
        "no_games_with_screenshots_found": "スクリーンショットフォルダのあるゲームが見つかりませんでした。",
        "unknown_game": "不明なゲーム (ID: {})",
        "thumbnail_fix_message": "「thumbnails」フォルダが選択されました。親フォルダが自動的に設定されました。"
    },
    "fr": {
        "window_title": "SteamF12TooL",
        "preview_placeholder": "L'image Sélectionnée Apparaîtra Ici",
        "select_image_button": "1. Sélectionner Image(s)",
        "multiple_images_selected": "{} images sélectionnées",
        "upload_progress": "Téléchargement : {}/{}",
        "batch_upload_complete": "{} images téléchargées avec succès.",
        "scan_games_button": "2. Scanner les Jeux Steam",
        "scan_games_button_scanning": "Scan en cours, veuillez patienter...",
        "manual_folder_button": "ou Sélectionner un Dossier Manuellement",
        "upload_button": "TÉLÉCHARGER LA SÉLECTION",
        "dark_mode_switch": "Mode Sombre",
        "edit_tools_label": "Outils d'Édition (Image unique)",
        "rotate_left_button": "Pivoter à Gauche",
        "rotate_right_button": "Pivoter à Droite",
        "reset_button": "Réinitialiser",
        "crop_button": "Recadrer",
        "crop_window_title": "Recadrer l'Image",
        "apply_button": "Appliquer",
        "cancel_button": "Annuler",
        "donate_button": "Faire un don",
        "donate_window_title": "Soutenir le Projet",
        "donate_main_text": "Si vous aimez ce projet, vous pouvez le soutenir\nen m'offrant un café. Merci pour votre soutien !",
        "donate_iban_label": "IBAN:",
        "donate_copy_button": "Copier l'IBAN",
        "donate_copy_success": "IBAN copié dans le presse-papiers !",
        "no_image_selected": "Aucune image sélectionnée.",
        "no_folder_selected": "Sélectionnez un jeu ou un dossier.",
        "game_combobox_default": "Scannez d'abord les jeux...",
        "game_combobox_select": "Sélectionnez un jeu...",
        "game_combobox_fail": "Le scan a échoué.",
        "select_profile": "Profil Steam",
        "no_profiles_found": "Aucun profil Steam trouvé.",
        "profile_fallback": "Profil ({})",
        "success": "Succès",
        "error": "Erreur",
        "warning": "Avertissement",
        "info": "Information",
        "fix": "Correction",
        "games_found_message": "{} jeux trouvés !",
        "select_image_warning": "Veuillez d'abord sélectionner un ou plusieurs fichiers image.",
        "select_folder_warning": "Veuillez sélectionner un jeu ou un dossier valide.",
        "upload_success_message": "Capture d'écran ajoutée avec succès :\n\n{}",
        "thumbnail_error": "Une erreur est survenue lors de la création de la miniature.",
        "unexpected_error": "Une erreur inattendue est survenue : {}",
        "steam_not_found": "Installation de Steam non trouvée.",
        "applist_download_fail": "Impossible de télécharger la liste des jeux Steam.",
        "applist_process_fail": "Impossible de traiter la liste des jeux : {}",
        "userdata_folder_not_found": "Dossier 'userdata' non trouvé.",
        "no_games_with_screenshots_found": "Aucun jeu avec des dossiers de captures d'écran n'a été trouvé.",
        "unknown_game": "Jeu Inconnu (ID: {})",
        "thumbnail_fix_message": "Le dossier 'thumbnails' a été sélectionné. Le dossier parent a été défini."
    },
    "ru": {
        "window_title": "SteamF12TooL",
        "preview_placeholder": "Выбранное изображение появится здесь",
        "select_image_button": "1. Выбрать изображение(я)",
        "multiple_images_selected": "Выбрано {} изображений",
        "upload_progress": "Загрузка: {}/{}",
        "batch_upload_complete": "Успешно загружено {} изображений.",
        "scan_games_button": "2. Сканировать игры Steam",
        "scan_games_button_scanning": "Сканирование, пожалуйста, подождите...",
        "manual_folder_button": "или Выбрать папку вручную",
        "upload_button": "ЗАГРУЗИТЬ ВЫБРАННОЕ",
        "dark_mode_switch": "Тёмный режим",
        "edit_tools_label": "Инструменты (только для одного изображения)",
        "rotate_left_button": "Влево",
        "rotate_right_button": "Вправо",
        "reset_button": "Сбросить",
        "crop_button": "Обрезать",
        "crop_window_title": "Обрезать изображение",
        "apply_button": "Применить",
        "cancel_button": "Отмена",
        "donate_button": "Пожертвовать",
        "donate_window_title": "Поддержать проект",
        "donate_main_text": "Если вам нравится этот проект, вы можете\nподдержать его, угостив меня кофе. Спасибо!",
        "donate_iban_label": "IBAN:",
        "donate_copy_button": "Копировать IBAN",
        "donate_copy_success": "IBAN скопирован в буфер обмена!",
        "no_image_selected": "Изображение не выбрано.",
        "no_folder_selected": "Выберите игру или укажите папку.",
        "game_combobox_default": "Сначала просканируйте игры...",
        "game_combobox_select": "Выберите игру...",
        "game_combobox_fail": "Ошибка сканирования.",
        "select_profile": "Профиль Steam",
        "no_profiles_found": "Профили Steam не найдены.",
        "profile_fallback": "Профиль ({})",
        "success": "Успех",
        "error": "Ошибка",
        "warning": "Предупреждение",
        "info": "Информация",
        "fix": "Исправление",
        "games_found_message": "Найдено {} игр!",
        "select_image_warning": "Пожалуйста, сначала выберите один или несколько файлов.",
        "select_folder_warning": "Пожалуйста, выберите действующую игру или папку.",
        "upload_success_message": "Скриншот успешно добавлен:\n\n{}",
        "thumbnail_error": "Произошла ошибка при создании миниатюры.",
        "unexpected_error": "Произошла непредвиденная ошибка: {}",
        "steam_not_found": "Установка Steam не найдена.",
        "applist_download_fail": "Не удалось загрузить список игр Steam.",
        "applist_process_fail": "Не удалось обработать список игр: {}",
        "userdata_folder_not_found": "Папка 'userdata' не найдена.",
        "no_games_with_screenshots_found": "Не найдено игр с папками скриншотов.",
        "unknown_game": "Неизвестная игра (ID: {})",
        "thumbnail_fix_message": "Была выбрана папка 'thumbnails'. Родительская папка была установлена."
    },
    "zh": {
        "window_title": "SteamF12TooL",
        "preview_placeholder": "选定的图片将显示在此处",
        "select_image_button": "1. 选择图片",
        "multiple_images_selected": "已选择 {} 张图片",
        "upload_progress": "上传中: {}/{}",
        "batch_upload_complete": "成功上传 {} 张图片。",
        "scan_games_button": "2. 扫描Steam游戏",
        "scan_games_button_scanning": "正在扫描，请稍候...",
        "manual_folder_button": "或手动选择文件夹",
        "upload_button": "上传所选内容",
        "dark_mode_switch": "深色模式",
        "edit_tools_label": "编辑工具 (仅限单张图片)",
        "rotate_left_button": "向左旋转",
        "rotate_right_button": "向右旋转",
        "reset_button": "重置",
        "crop_button": "裁剪",
        "crop_window_title": "裁剪图片",
        "apply_button": "应用",
        "cancel_button": "取消",
        "donate_button": "捐赠",
        "donate_window_title": "支持项目",
        "donate_main_text": "如果您喜欢这个项目，可以请我喝杯咖啡来支持它。\n谢谢您的支持！",
        "donate_iban_label": "IBAN:",
        "donate_copy_button": "复制IBAN",
        "donate_copy_success": "IBAN已复制到剪贴板！",
        "no_image_selected": "尚未选定图片。",
        "no_folder_selected": "请选择一个游戏或手动指定文件夹。",
        "game_combobox_default": "请先扫描游戏...",
        "game_combobox_select": "选择一个游戏...",
        "game_combobox_fail": "扫描失败。",
        "select_profile": "Steam个人资料",
        "no_profiles_found": "未找到Steam个人资料。",
        "profile_fallback": "个人资料 ({})",
        "success": "成功",
        "error": "错误",
        "warning": "警告",
        "info": "信息",
        "fix": "修正",
        "games_found_message": "找到 {} 个游戏！",
        "select_image_warning": "请先选择一个或多个图片文件。",
        "select_folder_warning": "请选择一个有效的游戏或文件夹。",
        "upload_success_message": "截图已成功添加：\n\n{}",
        "thumbnail_error": "创建缩略图时出错。",
        "unexpected_error": "发生意外错误：{}",
        "steam_not_found": "未找到Steam安装。请确保Steam已安装。",
        "applist_download_fail": "无法下载Steam游戏列表。请检查您的网络连接。",
        "applist_process_fail": "无法处理游戏列表：{}",
        "userdata_folder_not_found": "未找到 'userdata' 文件夹。",
        "no_games_with_screenshots_found": "未找到带有截图文件夹的游戏。",
        "unknown_game": "未知游戏 (ID: {})",
        "thumbnail_fix_message": "已选择 'thumbnails' 文件夹。父文件夹已自动设置。"
    }
}